# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, verbose_name='Designação')),
                ('cotation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Cotação')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Nota')),
                ('slug', models.SlugField(verbose_name='Caminho')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SchoolTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, verbose_name='Designação')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Classificação')),
                ('date', models.DateField(verbose_name='data')),
                ('contents', models.TextField(blank=True, verbose_name='Conteúdos')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('slug', models.SlugField(verbose_name='Caminho')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('school_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbook.SchoolTerm', verbose_name='Período')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbook.Student', verbose_name='Aluno')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbook.Subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Teste',
                'verbose_name_plural': 'Testes',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='school_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.SchoolTest', verbose_name='Teste'),
        ),
    ]
