# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltest',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Classificação'),
        ),
    ]
