# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbook', '0002_auto_20170809_1029'),
        ('grades', '0003_auto_20170809_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltest',
            name='school_class',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='tbook.SchoolClass', verbose_name='Turma'),
            preserve_default=False,
        ),
    ]
