# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Designação')),
                ('code', models.IntegerField(blank=True, verbose_name='Código da Escola')),
                ('adress', models.TextField(blank=True, verbose_name='Morada')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('admin_email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email Direção')),
                ('sevices_email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email Secretaria')),
                ('slug', models.SlugField(verbose_name='Caminho')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name_plural': 'Escolas',
                'ordering': ['name'],
                'verbose_name': 'Escola',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, verbose_name='Designação')),
                ('slug', models.SlugField(verbose_name='Caminho')),
                ('year_in_school', models.CharField(choices=[('7ºano', '7º Ano'), ('8ºano', '8º Ano'), ('9ºano', '9º Ano'), ('10ºano', '10º Ano'), ('11ºano', '11º Ano'), ('12ºano', '12º Ano')], default='7º Ano', max_length=100, verbose_name='Ano')),
                ('max_students', models.IntegerField(default=25, verbose_name='máx alunos')),
                ('teacher_in_charge', models.CharField(blank=True, max_length=100, verbose_name='Diretor de Turma')),
                ('tc_email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email DT')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbook.School', verbose_name='Escola')),
            ],
            options={
                'verbose_name_plural': 'Turmas',
                'ordering': ['designation'],
                'verbose_name': 'Turma',
            },
        ),
        migrations.CreateModel(
            name='SchoolTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('I', '1º Período'), ('II', '2º Período'), ('III', '3º Período')], default='1ºPeríodo', max_length=100, verbose_name='Designação')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(verbose_name='Fim')),
                ('slug', models.SlugField(verbose_name='Caminho')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name_plural': 'Períodos',
                'ordering': ['start_date'],
                'verbose_name': 'Período',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='Designação')),
                ('slug', models.SlugField(verbose_name='Caminho')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name_plural': 'Anos Letivos',
                'ordering': ['designation'],
                'verbose_name': 'Ano Letivo',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Telefone')),
                ('adress', models.TextField(blank=True, verbose_name='Morada')),
                ('number', models.IntegerField(verbose_name='Número na turma')),
                ('foto', models.ImageField(default='Stud_fotos/None/no-img.jpg', upload_to='Stud_Fotos/', verbose_name='Foto')),
                ('nee', models.BooleanField(default=False, verbose_name='NEE')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('tutor', models.CharField(max_length=100, verbose_name='Enc.Educação')),
                ('t_email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email EE')),
                ('t_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Telefone EE')),
                ('slug', models.SlugField(verbose_name='Caminho')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbook.SchoolClass', verbose_name='Turma')),
            ],
            options={
                'verbose_name_plural': 'Alunos',
                'ordering': ['school_class'],
                'verbose_name': 'Aluno',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('Math', 'Matemática'), ('Phys', 'Física'), ('Chem', 'Química'), ('Outra', 'Outra')], default='Física', max_length=100, verbose_name='Designação')),
                ('sigla', models.CharField(choices=[('Math', 'Mat'), ('Phys', 'Fis'), ('Chem', 'Quim'), ('Outra', 'Outra')], default='Fis', max_length=100, verbose_name='Nome Curto')),
                ('slug', models.SlugField(verbose_name='Caminho')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['designation'],
                'verbose_name': 'Disciplina',
            },
        ),
        migrations.AddField(
            model_name='schoolterm',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbook.SchoolYear', verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbook.SchoolYear', verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbook.Subject', verbose_name='Disciplina'),
        ),
    ]
