# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, verbose_name='Designação')),
                ('subjects', models.TextField(blank=True, verbose_name='Conteúdos')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('date', models.DateField(verbose_name='data')),
                ('slug', models.SlugField(verbose_name='Caminho')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Classificação')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Teste',
                'ordering': ['created'],
                'verbose_name_plural': 'Testes',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbook.SchoolClass', verbose_name='Turma')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbook.Student', verbose_name='Aluno')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbook.School_Test', verbose_name='Teste')),
            ],
        ),
    ]
