# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='designation',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Física', 'Física'), ('Química', 'Química'), ('Físico-Química', 'Físico-Química'), ('Outra', 'Outra')], default='Física', max_length=100, verbose_name='Designação'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sigla',
            field=models.CharField(choices=[('Mat', 'Mat'), ('Fis', 'Fis'), ('Quim', 'Quim'), ('FQ', 'FQ'), ('Outra', 'Outra')], default='Fis', max_length=100, verbose_name='Nome Curto'),
        ),
    ]
