# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbook', '0002_auto_20170809_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='7º Ano', max_length=100, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='schoolterm',
            name='designation',
            field=models.CharField(choices=[('1º Período', '1º Período'), ('2º Período', '2º Período'), ('3º Período', '3º Período')], default='1ºPeríodo', max_length=100, verbose_name='Designação'),
        ),
    ]
