# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbook', '0006_auto_20170817_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='foto',
            field=models.ImageField(default='media/fotos_alunos/no-img.jpg', upload_to='media/fotos_alunos/', verbose_name='Foto'),
        ),
    ]
